# Generated by Django 4.2.5 on 2023-09-13 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="file",
        ),
    ]
